[package]
name = "eventsphere-be"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
dashmap = "6.1.0"
lazy_static = "1.4.0"
reqwest = { version = "0.12", features = ["json"] }
getset = "0.1.2"
dotenvy = "0.15.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }