global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eventsphere-be'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
