global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert rules configuration
rule_files:
  - /etc/prometheus/alerting/alerts.yml

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'eventsphere-be'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['eventsphere-be:8000']
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
      
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
      
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
