global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'email-notifications'
    group_wait: 10s
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: 'slack-notifications'
    group_wait: 30s
    repeat_interval: 3h

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'alerts@yourdomain.com'
    from: 'alertmanager@yourdomain.com'
    smarthost: 'smtp.example.com:587'
    auth_username: '${SMTP_USERNAME}'
    auth_password: '${SMTP_PASSWORD}'
    send_resolved: true
    headers:
      Subject: "[ALERT] - {{ .GroupLabels.alertname }}"
    html: |
      <!DOCTYPE html>
      <html>
      <body>
        <h1>{{ .GroupLabels.alertname }}</h1>
        <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
        <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
        <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
        <ul>
          {{range .Alerts}}
            <li>Started: {{.StartsAt}}</li>
          {{end}}
        </ul>
      </body>
      </html>

- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
    channel: '#alerts'
    send_resolved: true
    title: "{{ .GroupLabels.alertname }}"
    text: |
      {{ .CommonAnnotations.summary }}
      {{ .CommonAnnotations.description }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname']
