# File path: .github/workflows/deploy-prod.yml

name: Deploy to Production

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: "The branch or tag ref to deploy"

jobs:
  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yourusername/yourapp:latest,yourusername/yourapp:${{ github.sha }}
      
      # Add your production environment deployment steps here
      - name: Deploy to production environment
        run: echo "Deploying to production environment..."