# File path: .github/workflows/sonarcloud.yml

name: SonarCloud Analysis

on:
  workflow_call:
    outputs:
      sonar_success:
        description: "Indicates if sonar scan was successful"
        value: ${{ jobs.sonarcloud.outputs.sonar_success }}

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    outputs:
      sonar_success: ${{ steps.set_success.outputs.sonar_success }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: .
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=your-project-key
            -Dsonar.organization=your-organization
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.rust.coverage.reportPaths=lcov.info

      - name: Set sonar success output
        id: set_success
        run: echo "sonar_success=true" >> $GITHUB_OUTPUT